### ISSUE TITLE
Greeter crashes on Startup

### ISSUE THREAD

**Issue by mrosmarin** [spring-cloud-services-samples/greeting#11]
this is the log. 

Message Generation is working fine.

2017-03-30T13:10:54.999-04:00 [APP/0] [OUT] 2017-03-30 17:10:54.999 ERROR 19 --- [ main] o.s.b.f.s.DefaultListableBeanFactory : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception
2017-03-30T13:10:54.999-04:00 [APP/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:417) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:54.999-04:00 [APP/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
2017-03-30T13:10:54.999-04:00 [APP/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [app/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@21bcffb5: startup date [Thu Mar 30 17:10:54 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@69222c14
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:818) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [app/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at greeter.GreeterApplication.main(GreeterApplication.java:37) [classes/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
2017-03-30T13:10:55.000-04:00 [APP/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
2017-03-30T13:10:55.000-04:00 [APP/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-03-30T13:10:55.000-04:00 [APP/0] [ERR] Exception in thread "main" java.lang.reflect.InvocationTargetException
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.lang.reflect.Method.invoke(Method.java:498)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.lang.ClassLoader.defineClass1(Native Method)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/client/loadbalancer/LoadBalancerRequestTransformer
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2017-03-30T13:10:55.001-04:00 [APP/0] [ERR] at java.security.AccessController.doPrivileged(Native Method)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at java.lang.Class.getDeclaredMethods(Class.java:1975)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
2017-03-30T13:10:55.002-04:00 [APP/0] [ERR] at java.lang.Class.getDeclaredMethods0(Native Method)
2017-03-30T13:10:55.003-04:00 [APP/0] [ERR] at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
2017-03-30T13:10:55.003-04:00 [APP/0] [ERR] at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
2017-03-30T13:10:55.003-04:00 [APP/0] [ERR] at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570)
2017-03-30T13:10:55.003-04:00 [APP/0] [ERR] at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
2017-03-30T13:10:55.003-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:694)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:420)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:886)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:872)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:812)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:858)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1456)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:501)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1189)
2017-03-30T13:10:55.004-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
2017-03-30T13:10:55.006-04:00 [APP/0] [ERR] at greeter.GreeterApplication.main(GreeterApplication.java:37)
2017-03-30T13:10:55.006-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
2017-03-30T13:10:55.006-04:00 [APP/0] [ERR] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
2017-03-30T13:10:55.006-04:00 [APP/0] [ERR] ... 8 more
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.loadbalancer.LoadBalancerRequestTransformer
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-03-30T13:10:55.007-04:00 [APP/0] [ERR] ... 44 more
2017-03-30T13:10:55.047-04:00 [APP/0] [OUT] Exit status 1
2017-03-30T13:10:55.056-04:00 [CELL/0] [OUT] Exit status 0
2017-03-30T13:10:55.090-04:00 [CELL/0] [OUT] Destroying container
2017-03-30T13:10:55.103-04:00 [API/1] [OUT] App instance exited with guid e9c85d72-5033-4ccf-b238-32eb16c0dc36 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>7, "crash_timestamp"=>1490893855063171353, "version"=>"52ab1d0b-84c8-40c4-8876-dc983b75419c"}
2017-03-30T13:10:55.600-04:00 [CELL/0] [OUT] Successfully destroyed container

**Comment by vladimirconev** [comment]
In pom.xml of greeter module I've modified version of spring-cloud-dependencies artifact in dependency management section as follows:
 <version>Camden.SR4</version>
Please give it a try and if it is ok I can create a pull request.

**Comment by lineshmehta5** [comment]
This is due to the version of org.springframework.cloud.
Update the pom.xml for org.springframework.cloud with version as SR4 instead of SR3.
Tip: Compare the message and greeter pom.xml and match it
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Camden.SR4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

**Comment by royclarkson** [comment]
Appears to be resolution to this. Please open a new issue if you continue to experience problems. Thanks.
