### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by kdvolder** [spring-cloud-services-samples/greeting#2]
I tried deploying the samples to PEZ but all I can get them to do is throw NPEs:

```
    2015-08-28T13:59:22.84-0700 [App/0]      OUT java.lang.NullPointerException: null
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    2015-08-28T13:59:22.84-0700 [App/0]      OUT    at camelboy.CamelboyApplication.main(CamelboyApplication.java:31)
```

**Comment by kdvolder** [comment]
Looks like @spencergibb fix applied to spring-cloud-commons fixes this problem.

**Comment by kdvolder** [comment]
Sorry... issue is actually not fixed yet, at least not in this sample app. After overcoming issue #3 the NPE is back again.

**Comment by spencergibb** [comment]
@kdvolder My guess is it might be a NPE somewhere else, but not on the same line.

**Comment by kdvolder** [comment]
Right: I should have attached trace.

        2015-08-31T10:54:05.30-0700 [App/0]      ERR java.lang.reflect.InvocationTargetException
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at java.lang.Thread.run(Thread.java:745)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR Caused by: java.lang.NullPointerException
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)
        2015-08-31T10:54:05.30-0700 [App/0]      ERR 	... 6 more

**Comment by kdvolder** [comment]
Right. This is what I get now:

        java.lang.NullPointerException: null
	        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
	        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.lang.reflect.Method.invoke(Method.java:497)
	        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	        at java.lang.Thread.run(Thread.java:745)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        Caused by: java.lang.NullPointerException
	        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
	        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81)
	        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	        at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)

**Comment by kdvolder** [comment]
Sorry I deleted the message. Because the stacktraces got 'jumbled up'. This is what I get now. It looks like the same line still. Maybe the fix has not yet percolated through snapshot repos? I did clear out my maven cache prior do doing this test. Attaching trace again. It looks like the same line:

        2015-08-31T11:33:25.71-0700 [App/0]      OUT java.lang.NullPointerException: null
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at java.lang.reflect.Method.invoke(Method.java:497)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        2015-08-31T11:33:25.71-0700 [App/0]      OUT 	at java.lang.Thread.run(Thread.java:745)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR java.lang.reflect.InvocationTargetException
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at java.lang.Thread.run(Thread.java:745)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR Caused by: java.lang.NullPointerException
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:127)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:116)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:81)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        2015-08-31T11:33:25.71-0700 [App/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        2015-08-31T11:33:25.72-0700 [App/0]      ERR 	at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)
        2015-08-31T11:33:25.72-0700 [App/0]      ERR 	... 6 more

**Comment by spencergibb** [comment]
No, it's in snapshots. That line can't have a NPE, because the same object is used on 126.

**Comment by kdvolder** [comment]
Cracked open the 'jar' the samples produces when I build it and found this inside:

spring-cloud-commons-1.0.2.RELEASE.jar

I guess that explains it.

**Comment by spencergibb** [comment]
yup, good to know.

**Comment by kdvolder** [comment]
I tried to stick a 1.1.0.BUILD-SNAPSHOT for spring-cloud-commons and spring-cloud-context into the pom. This gets me passed the NPE.

But the sample still doesn't work. Now it seems to be having trouble with oauth tokens for the eureka service. 

2015-08-31T12:58:35.42-0700 [App/0]      OUT 2015-08-31 19:58:35.426 ERROR 29 --- [           main] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://uP1ojK0mMkuH:Rwp0ydhAovSP@eureka-eccc183e-3993-4aa5-ae81-55b0ae70514b.cfapps.pez.pivotal.io/eureka/apps/
        2015-08-31T12:58:35.42-0700 [App/0]      OUT Can't contact any eureka nodes - possibly a security group issue?
        2015-08-31T12:58:35.42-0700 [App/0]      OUT java.lang.NullPointerException: null
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.getAccessTokenUri(OAuth2AccessTokenSupport.java:162)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsAccessTokenProvider.obtainAccessToken(ClientCredentialsAccessTokenProvider.java:44)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:142)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:118)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at io.pivotal.spring.cloud.service.eureka.EurekaOAuth2RequestDecorator.getHeaders(EurekaOAuth2RequestDecorator.java:36)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at io.pivotal.spring.cloud.service.eureka.ClientFilterAdapter.handle(ClientFilterAdapter.java:24)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.sun.jersey.api.client.Client.handle(Client.java:648)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.netflix.discovery.DiscoveryClient.getUrl(DiscoveryClient.java:1567)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1113)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at java.lang.reflect.Method.invoke(Method.java:497)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:202)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at io.pivotal.spring.cloud.service.eureka.EurekaOAuth2ReflectionShim$1.fetchRegistry(EurekaOAuth2ReflectionShim.java:90)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at io.pivotal.spring.cloud.service.eureka.EurekaOAuth2ReflectionShim$1.init(EurekaOAuth2ReflectionShim.java:71)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:129)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:770)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at java.lang.reflect.Method.invoke(Method.java:497)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        2015-08-31T12:58:35.42-0700 [App/0]      OUT 	at java.lang.Thread.run(Thread.java:745)

I'm giving up. I just can't get this @#$$@#$ sample code to work.
