### ISSUE TITLE
Sample fails to start 'because no Bean Validation provider could be found'

### ISSUE THREAD

**Issue by kdvolder** [spring-cloud-services-samples/greeting#3]
Thanks for fixing the NPE I ran into on friday. I still can't start the sample however. The error this time is different though:

```
    2015-08-31T09:48:02.93-0700 [App/0]      ERR SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    2015-08-31T09:48:02.93-0700 [App/0]      ERR SLF4J: Defaulting to no-operation (NOP) logger implementation
    2015-08-31T09:48:02.93-0700 [App/0]      ERR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    2015-08-31T09:48:04.60-0700 [App/0]      ERR java.lang.reflect.InvocationTargetException
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:497)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at java.lang.Thread.run(Thread.java:745)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:199)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:126)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:75)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:55)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:285)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at expedition.ExpeditionApplication.main(ExpeditionApplication.java:24)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    ... 6 more
    2015-08-31T09:48:04.60-0700 [App/0]      ERR Caused by: javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:271)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:381)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:174)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
    2015-08-31T09:48:04.60-0700 [App/0]      ERR    ... 29 more
    2015-08-31T09:48:04.61-0700 [App/0]      OUT 
    2015-08-31T09:48:04.64-0700 [DEA/6]      ERR Instance (index 0) failed to start accepting connections
```

**Comment by kdvolder** [comment]
From searching stackoverflow on the error message:

Adding this to the pom:
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator-annotation-processor</artifactId>
			<version>4.1.0.Final</version>
		</dependency>

Seems to fix the error.

**Comment by nan403** [comment]
Thank you, I solved the same problem

**Comment by wanggang0321** [comment]
whr "Add a provider like Hibernate Validator (RI) to your classpath"????

**Comment by wanggang0321** [comment]
why  "Add a provider like Hibernate Validator (RI) to your classpath" ???
